version: "3.8"
services:
  backend_server:
    restart: "on-failure"
    build:
      context: "./back"
      dockerfile: Dockerfile
    container_name: "node-pill-my-rhythm-app"
    ports:
      - 5000:5000
    links:
      - ai_server

  ai_server:
    restart: "on-failure"
    build:
      context: "./ai"
      dockerfile: Dockerfile
    container_name: "python-pill-my-rhythm-app"
    ports:
      - 5005:5005
    links:
      - backend_server
